### PR TITLE
Add tracking area to custom button

### PR DESCRIPTION
**Pull request by boyvanamstel**
Resolves https://github.com/sindresorhus/CircularProgress/pull/4#issuecomment-458431791

We could probably use the tracking area in the `CircularProgress` view as well, but that would require customizing `CustomButton` just for this.

### CODE REVIEW

**Comment by boyvanamstel** [comment]
I'll add this to Gifski when it's merged here.

**Comment by sindresorhus** [comment]
> You should override this method to remove out of date tracking areas and add recomputed tracking areas; **your implementation should call super.**
\- https://developer.apple.com/documentation/appkit/nsview/1483719-updatetrackingareas#

**Comment by sindresorhus** [comment]
Works perfectly 👌

**Comment by boyvanamstel** [comment]
> Works perfectly 👌

Thanks 👍

**Comment by sindresorhus** [comment]
https://github.com/realm/SwiftLint/issues/2616

**Pull request merged**
